apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xtgviycdw-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tnevrlka-rhtap/rhtap-qe-go:10376abf7ac1a18b0855cd7dcdbd8ed4c965dc99@sha256:c1c8b0c4031d1f49a46411c175cd2710ffcfb310866b7541a537c7f6233d1223
          name: container-image
